// <auto-generated />
using System;
using DuckBill.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DuckBill.Infrastructure.Migrations
{
    [DbContext(typeof(DuckBillDbContext))]
    [Migration("20251007142916_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DuckBill.Domain.Entities.Ativo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MoedaBase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasDefaultValue("BRL")
                        .HasColumnName("MOEDA_BASE");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("NVARCHAR2(12)")
                        .HasColumnName("TICKER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("ATIVO", (string)null);
                });

            modelBuilder.Entity("DuckBill.Domain.Entities.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("CATEGORIA", (string)null);
                });

            modelBuilder.Entity("DuckBill.Domain.Entities.CotacaoAtivo", b =>
                {
                    b.Property<long>("AtivoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ATIVO_ID");

                    b.Property<DateTime>("DataRef")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_REF");

                    b.Property<decimal>("PrecoFech")
                        .HasColumnType("NUMBER(14,6)")
                        .HasColumnName("PRECO_FECH");

                    b.HasKey("AtivoId", "DataRef");

                    b.ToTable("COTACAO_ATIVO", (string)null);
                });

            modelBuilder.Entity("DuckBill.Domain.Entities.Despesa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoriaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CATEGORIA_ID");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_COMPRA");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasDefaultValue("BRL")
                        .HasColumnName("MOEDA");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USUARIO_ID");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DESPESA", (string)null);
                });

            modelBuilder.Entity("DuckBill.Domain.Entities.TransacaoAtivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AtivoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ATIVO_ID");

                    b.Property<DateTime>("DataNegocio")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_NEGOCIO");

                    b.Property<decimal>("Preco")
                        .HasColumnType("NUMBER(14,6)")
                        .HasColumnName("PRECO");

                    b.Property<decimal>("Qtd")
                        .HasColumnType("NUMBER(12,4)")
                        .HasColumnName("QTD");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("NVARCHAR2(4)")
                        .HasColumnName("TIPO");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TRANSACAO_ATIVO", (string)null);
                });

            modelBuilder.Entity("DuckBill.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("SENHA");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("DuckBill.Domain.Entities.CotacaoAtivo", b =>
                {
                    b.HasOne("DuckBill.Domain.Entities.Ativo", "Ativo")
                        .WithMany("Cotacoes")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ativo");
                });

            modelBuilder.Entity("DuckBill.Domain.Entities.Despesa", b =>
                {
                    b.HasOne("DuckBill.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Despesas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DuckBill.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DuckBill.Domain.Entities.TransacaoAtivo", b =>
                {
                    b.HasOne("DuckBill.Domain.Entities.Ativo", "Ativo")
                        .WithMany("Transacoes")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DuckBill.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ativo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DuckBill.Domain.Entities.Ativo", b =>
                {
                    b.Navigation("Cotacoes");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("DuckBill.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
